language: python

addons:
  apt:
    packages:
      - graphviz

python:
  - "3.5"
  - "3.6"

install:
  - pip install tox

env:
  - TOXENV=test
  - TOXENV=build_docs


script:
  - tox -e $TOXENV -vv
