[build-system]
requires = ["setuptools",
            "setuptools_scm",
            "wheel",
            "cython",
            "jinja2",
            "oldest-supported-numpy",
            "git+https://github.com/astropy/astropy-helpers@extension-helpers"]
build-backend = 'setuptools.build_meta'

